config/routes.rb
Rails.application.routes.draw do
  root   'hotels#top'
  get    'signup' => 'users#new'
  post   'signup' => 'users#create'
  get    'login'  => 'sessions#new'
  post   'login'  => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users, only: [:show]
  resources :hotels do
    resources :comments
  end
end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :hotel
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates  :text,   presence: true
  validates  :rating, presence: true
  validates  :user,   presence: true
  belongs_to :hotel
  belongs_to :user
end

app/models/hotel.rb
class Hotel < ActiveRecord::Base
  validates :title,   presence: true
  validates :rating,  presence: true
  validates :price,   presence: true, numericality: { greater_than: 0 }
  validates :picture, format: { with: %r{\.(gif|jpg|jpeg|png)\Z}i,
                                message: "must be JPG, GIF or PNG." }

  belongs_to :user
  has_one    :address
  has_many   :comments
  accepts_nested_attributes_for :address, allow_destroy: true
  
  def full_address
    hotel = self.address
    if hotel
      "#{hotel.country} #{hotel.state} #{hotel.city} #{hotel.street}"
    else
      "unknown"
    end
  end
  
  def self.top
    self.order('rating desc').limit(5)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :name,     presence: true, length: { maximum: 50 }
  validates :email,    presence: true, length: { maximum: 255 },
                       format: { with: VALID_EMAIL_REGEX },
                       uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  has_secure_password
  has_many :hotels
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate_user

  def create
    hotel = Hotel.find(params[:hotel_id])
    comment = hotel.comments.new(comment_params)
    comment.user_id = current_user.id
    if comment.save
      hotel_rating_update(hotel)
      redirect_to hotel, notice: "Thanks! Your comment successfully added."
    else
      redirect_to hotel, alert: "The comment can't be blank."
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:rating, :text)
  end
  
  def hotel_rating_update(hotel)
    new_rating = (hotel.rating + hotel.comments.sum(:rating)) / 
                 (hotel.comments.count + 1)
    hotel.update_attribute(:rating, new_rating)
  end
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_action :authenticate_user, only: [:new, :create]

  def top
    @hotels = Hotel.top
  end

  def index
    @hotels = Hotel.includes(:address).all
  end

  def show
    @hotel = Hotel.find(params[:id])
    @comments = @hotel.comments
  end

  def new
    @hotel = Hotel.new
    @hotel.build_address
  end

  def create
    @hotel = current_user.hotels.new(hotel_params)
    @hotel.picture = upload_picture(params[:hotel][:picture])
    if @hotel.save
      redirect_to @hotel, notice: "The hotel successfully added"
    else
      flash.now[:alert] = "You have some errors!"
      render :new
    end
  end

  private

  def hotel_params
    params.require(:hotel).permit(:title, :rating, :breakfast,
                           :room_description, :price, address_attributes: 
                           [:country, :state, :city, :street])
  end
  
  def upload_picture(image)
    image_name = (Time.now.to_i.to_s + 
                  File.extname(image.original_filename)).downcase
    File.open(Rails.root.join('public', 'uploads', image_name), 'wb') do |file|
      file.write(image.read)
    end
    image_name
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      log_in(user)
      redirect_to user, notice: "Welcome back, #{user.name}!"
    else
      flash.now[:alert] = "Combination Email/Password is invalid!"
      render :new
    end
  end
  
  def destroy
    log_out
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :registered_user, only: [:new, :create]
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user, notice: "Welcome to Hotelgator, #{@user.name}!"
    else
      flash.now[:alert] = "You have some errors!"
      render :new
    end
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, 
                                                :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = "Hotelgator"
    if page_title.empty?
      "#{base_title}"
    else
      "#{base_title} · #{page_title}"
    end
  end
  
  def boolean_human(boolean)
    if boolean
      "Yes"
    else
      "No"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    current_user != nil
  end
  
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  
  private
  
  def authenticate_user
    redirect_to login_path, notice: "Please, log in." unless logged_in?
  end
  
  def registered_user
    redirect_to user_path(current_user) if logged_in?
  end
end

app/views/comments/_comment.html.erb
<% @comments.each do |comment| %>
<div class="comments">
  <div class="author">
    <%= image_tag comment.user.avatar, alt: comment.user.name %>
    <%= comment.user.name %>
    <p>My rating <%= pluralize(comment.rating, "Star") %></p>
    <p><%= time_ago_in_words(comment.created_at) %> ago</p>
  </div>
  <div class="comment">
    <%= comment.text %>
  </div>
</div>
<% end %>

app/views/comments/_form.html.erb
<h3>Your comment and rating</h3>
<% if logged_in? %>
  <%= form_for :comment, url: hotel_comments_path(@hotel), 
                         html: { class: "form" } do |f| %>
    <div class="radio_inline">
      <% ['5', '4', '3', '2', '1'].each do |star| %>
        <%= f.radio_button :rating, star, checked: (star == '5') %> <%= star %>
      <% end %>
    </div>
    <%= f.text_area :text %>
    <%= f.submit "Leave comment" %>
  <% end %>
<% else %>
  <center>Please, <%= link_to 'log in', login_path %> for comment.</center>
<% end %>

app/views/hotels/_error.html.erb
<% if @hotel.errors.any? %>
<div class="errors">
  Form contains <%= pluralize(@hotel.errors.count, "error") %>:
  <ul>
    <% @hotel.errors.full_messages.each do |msg| %>
    <li>- <%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/hotels/index.html.erb
<% provide(:title, "All hotels") %>
<h1>All hotels</h1>

<% @hotels.each do |hotel| %>
  <article>
    <h2><%= link_to hotel.title, hotel %></h2>
    <%= image_tag "/uploads/#{hotel.picture}", alt: hotel.title %>
    <p>Rating: <strong><%= pluralize(hotel.rating, "Star") %></strong></p>
    <% if hotel.address %>
    <p><%= "#{hotel.address.country}, #{hotel.address.city}" %></p>
    <% end %>
    <p><%= link_to "Read comments", hotel %></p>
  </article>
<% end %>

app/views/hotels/new.html.erb
<% provide(:title, "Add hotel") %>
<h1>Add hotel</h1>

<%= form_for @hotel, html: { class: "form", multipart: "true" } do |f| %>

  <%= render 'error' %>
  
  <%= f.label :title %>
  <%= f.text_field :title %>
  
  <%= f.label :rating %>
  <div class="radio_inline">
    <% ['5', '4', '3', '2', '1'].each do |star| %>
      <%= f.radio_button :rating, star, checked: (star == '5') %> <%= star %>
    <% end %>
  </div>
  
  <%= f.label :breakfast, "Breakfast included?" %>
  <%= f.check_box :breakfast %>
  
  <%= f.label :room_description %>
  <%= f.text_area :room_description %>
  
  <%= f.label :price, "Room price, $" %>
  <%= f.number_field :price %>
  
  <%= f.label :picture %>
  <%= f.file_field :picture %>
  
  <%= f.fields_for :address do |address_form| %>

    <%= address_form.label :country %>
    <%= address_form.text_field :country %>

    <%= address_form.label :state %>
    <%= address_form.text_field :state %>

    <%= address_form.label :city %>
    <%= address_form.text_field :city %>
    
    <%= address_form.label :street %>
    <%= address_form.text_field :street %>

  <% end %>
  
  <%= f.submit "Add hotel" %>

<% end %>

app/views/hotels/show.html.erb
<% provide(:title, "Hotel · #{@hotel.title}") %>
<h1><%= @hotel.title %></h1>

<div class="content">
  <div class="photo">
    <%= image_tag "/uploads/#{@hotel.picture}", alt: @hotel.title %>  
  </div>
  <div class="hotel">
    <ul>
      <li>Hotel rating: <strong><%= pluralize(@hotel.rating, "Star") %></strong></li>
      <li>Hotel address: <strong><%= @hotel.full_address %></strong></li>
      <li>Breakfast included: <strong><%= boolean_human(@hotel.breakfast) %></strong></li>
      <li>Price: <strong><%= number_to_currency(@hotel.price) %></strong></li>
      <li>
        Room description:
        <p><%= @hotel.room_description %></p>
      </li>
      <li>Added by <%= link_to @hotel.user.name, user_path(@hotel.user) %></li>
    </ul>
  </div>
</div>

<section>
  <%= render 'comments/form' %>
  <%= render 'comments/comment' %>
</section>

app/views/hotels/top.html.erb
<h1>Top 5 hotels</h1>

<ol>
<% @hotels.each do |hotel| %>
  <li>
    <%= link_to hotel.title, hotel %>
    (<%= pluralize(hotel.rating, "Star") %>)
  </li>
<% end %>
</ol>

<p><%= link_to "All hotels", hotels_path %></p>

app/views/layouts/_footer.html.erb
<footer>
  &copy; <%= Time.now.year %> by Hotelgator
  <nav>
    <ul>
      <% if logged_in? %>
      <li>Logged as <%= current_user.email %></li>
      <% end %>
      <li><%= link_to 'About', '#' %></li>
      <li><%= link_to 'Contact', '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <%= link_to 'Hotelgator', root_path, class: "logo" %>
  <nav>
    <ul>
      <li><%= link_to 'Home',      root_path %></li>
      <% if logged_in? %>
      <li><%= link_to 'Add hotel', new_hotel_path %></li>
      <li><%= link_to 'Profile',   user_path(current_user) %></li>
      <li><%= link_to 'Logout',    logout_path, method: :delete %></li>
      <% else %>
      <li><%= link_to 'Sign up',   signup_path %></li>
      <li><%= link_to 'Log in',    login_path %></li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 
                                            'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <section>
  <% flash.each do |name, msg| %>
    <%= content_tag(:div, msg, class: "flash #{name}") %>
  <% end %>
  
  <%= yield %>
  </section>
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/users/_error.html.erb
<% if @user.errors.any? %>
<div class="errors">
  Form contains <%= pluralize(@user.errors.count, "error") %>:
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
    <li>- <%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/users/new.html.erb
<% provide(:title, "Sign up") %>
<h1>Sign up</h1>

<%= form_for @user, url: signup_path, html: { class: "form" } do |f| %>

  <%= render 'error' %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "Sign up" %>

<% end %>

app/views/users/show.html.erb
<% provide(:title, "Profile · #{@user.name}") %>
<%= image_tag @user.avatar, alt: @user.name, class: "avatar" %>
<h1><%= @user.name %></h1>
<h2>My hotels:</h2>
<ul>
<% @user.hotels.each do |hotel| %>
  <li><%= link_to hotel.title, hotel %></li>
<% end %>
</ul>
<h2>My comments:</h2>
<ul>
<% @user.comments.each do |comment| %>
  <li><%= link_to comment.hotel.title, comment.hotel %></li>
<% end %>
</ul>